// types/Job.ts
export const jobStatusOptions = [
  'applied',
  'got interview',
  'interviewed',
  'rejected',
  'got offer',
] as const; // <-- 'as const' makes it readonly literal strings

export type JobStatus = typeof jobStatusOptions[number]; 
// JobStatus becomes: 'applied' | 'got interview' | ...

export interface Job {
  id?: number; // optional, generated by backend
  companyName: string;
  jobTitle: string;
  status: JobStatus;
  appliedDate: string; // ISO string (e.g., "2025-05-15")
  notes?: string;
}
