// src/types/Job.ts

export type JobStatus =
  | 'applied'
  | 'got interview'
  | 'interviewed'
  | 'rejected'
  | 'got offer';

export interface Job {
  id?: number; // optional, generated by backend
  companyName: string;
  jobTitle: string;
  status: JobStatus;
  appliedDate: string; // ISO string (e.g., "2025-05-15")
  notes?: string;
}
